# Generated by Django 6.0.5 on 2026-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nole', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
